; cube.asm -- rotating wireframe cube: the first 3D milestone
;
; MODE 4, full takeover, double buffering on the two hardware screens
; (docs/takeover.md), built on the measured line budget in
; docs/vector-perf.md: at ~90 px edges the cube costs ~1.8 frames to
; erase + transform + draw, so it runs at a steady 25 Hz -- only
; complete frames are ever shown. Getting it to 50 Hz is future work.
;
; Per frame, into the back buffer:
;   1. erase: long-word clear of the bounding box the cube had in THIS
;      buffer two frames ago (32-px-aligned spans; far cheaper than
;      redrawing the old edges in black -- and the reason the cube is
;      WHITE: both planes clear together)
;   2. rotate: yaw then pitch, 8.8 fixed-point sin/cos from sintab
;      (sin.inc, generated by tools/gensin.py)
;   3. project: perspective, px = 256 + x'*256/(Z0+z), and the y focal
;      length scaled to 170 (~2/3) because mode 4 pixels are ~2/3 as
;      wide as tall on a 4:3 screen -- the cube LOOKS cubic
;   4. backface culling, Elite/Starglider style: every face is wound
;      consistently as seen from outside, so face f is front-facing iff
;      its PROJECTED winding keeps its sign -- one 2D cross product per
;      face, no normals. Each edge carries a mask of its two faces and
;      is drawn only if at least one is visible: for a convex solid
;      that IS exact hidden-line removal (~9 of 12 edges drawn).
;   4b. draw the visible edges with lib/draw_line_w.asm (white, shallow
;      lines through the byte-granular fast path). Rotation advances by
;      the previous loop's BEAT count, so the spin speed stays constant
;      in time even when the frame rate mixes 50 and 25 Hz.
;   5. instrumentation: the live headroom bar (game8's gauge: idle
;      spins in the VBL wait) plus two 64-loop-averaged binary meters
;      (the lines/ readout) -- avg idle spins, and 2-beat loops out of
;      64 (0 = solid 50 Hz, 64 = solid 25 Hz). See draw_meters.
;
; No clipping: S/Z0/focal are chosen so the projection stays on screen
; (max extent x 256+-98, y 120+-66) clear of the bar rows.
;
; Assemble: vasmm68k_mot -m68008 -Fbin -o cube_bin cube.asm

; hardware
mc_stat     equ     $18063          ; ZX8301 display control (write-only)
pc_intr     equ     $18021          ; ZX8302 interrupt register
pc__frame   equ     3               ; bit 3 = 50/60 Hz frame interrupt

scr0        equ     $20000          ; screen 0 (displayed at boot)
scr1        equ     $28000          ; screen 1 (ex-QDOS sysvars, now ours)
scr_llen    equ     128             ; bytes per scan line

; cube geometry / projection (see the no-clipping note above)
csize       equ     48              ; half edge: vertices at (+-48)^3
zdist       equ     300             ; Z0: eye distance to cube centre
xfocal      equ     256             ; px = 256 + x'*xfocal/(Z0+z)
yfocal      equ     170             ; py = 120 + y'*yfocal/(Z0+z)
ctr_x       equ     256
ctr_y       equ     120

; angles are 8.8 fixed-point brads (65536 units = a full turn, so word
; wrap-around IS the modulo); steps are per BEAT (20 ms), scaled by the
; previous loop's beat count -- constant speed in time at any frame rate
da          equ     256             ; yaw: 1 brad/beat (2.5 turns/min)
db          equ     384             ; pitch: 1.5 brads/beat

; headroom bar (game8 calibration: ~1000 idle spins = a whole free frame)
hb_y        equ     252             ; bar top line (2 rows tall)
hb_shift    equ     4

; ---------------------------------------------------------------- job header
start:
        bra.s   main
        dc.l    0
        dc.w    $4afb               ; "job name follows" flag
        dc.w    jobname_e-jobname
jobname:
        dc.b    'Cube'
jobname_e:
        even

; ----------------------------------------------------------------- take over
main:
        trap    #0                  ; QDOS: enter supervisor mode
        move.w  #$2700,sr           ; mask all interrupts -- QDOS is gone
        lea     sv_stack_top(pc),sp ; run on our own supervisor stack

        move.b  #0,mc_stat          ; mode 4, screen 0 displayed

        lea     scr0,a0             ; clear BOTH screens ($20000-$2FFFF)
        move.w  #$10000/4-1,d0
        moveq   #0,d1
.clr:   move.l  d1,(a0)+
        dbf     d0,.clr

        move.b  #1<<pc__frame,pc_intr   ; discard any pending frame bit
        moveq   #1,d7               ; back buffer index: screen 1

; ---------------------------------------------------------------- frame loop
frame_loop:
        lea     scr0,a4             ; a4 = back buffer base
        tst.w   d7
        beq.s   .bb0
        lea     scr1,a4
.bb0:
; ----- erase the cube this buffer held two frames ago: movem-clear its
; bounding box rows (bbox: miny, nrows, end-of-span offset, 36-byte
; chunk count-1; nrows = 0 -> nothing yet). Nothing is live at the top
; of the frame, so nine registers hold zeros with no saving; each
; predecrementing movem clears 36 bytes. Spans round UP to chunks and
; may spill into the next row's left edge -- harmless, everything in
; the cube's rows outside the box is already black.
        lea     bbox0(pc),a2
        move.w  d7,d0
        lsl.w   #3,d0
        adda.w  d0,a2               ; a2 = bbox[d7]
        move.w  (a2)+,d1            ; miny
        move.w  (a2)+,d2            ; nrows
        beq     .noer
        move.w  (a2)+,d3            ; end-of-span offset in the row
        move.w  (a2),d4             ; chunk count - 1 (0..3)
        lsl.w   #7,d1
        add.w   d3,d1
        lea     (a4,d1.w),a0        ; end of the first row's span
        moveq   #0,d0               ; nine zeros for the bursts
        moveq   #0,d1
        moveq   #0,d3
        moveq   #0,d5
        moveq   #0,d6
        suba.l  a1,a1
        suba.l  a2,a2
        suba.l  a3,a3
        suba.l  a5,a5
        tst.w   d4                  ; pick the row loop for the width
        beq.s   .c1
        subq.w  #1,d4
        beq.s   .c2
        subq.w  #1,d4
        beq.s   .c3
.c4:    movem.l d0-d1/d3/d5-d6/a1-a3/a5,-(a0)
        movem.l d0-d1/d3/d5-d6/a1-a3/a5,-(a0)
        movem.l d0-d1/d3/d5-d6/a1-a3/a5,-(a0)
        movem.l d0-d1/d3/d5-d6/a1-a3/a5,-(a0)
        lea     scr_llen+144(a0),a0
        subq.w  #1,d2
        bne.s   .c4
        bra.s   .noer
.c3:    movem.l d0-d1/d3/d5-d6/a1-a3/a5,-(a0)
        movem.l d0-d1/d3/d5-d6/a1-a3/a5,-(a0)
        movem.l d0-d1/d3/d5-d6/a1-a3/a5,-(a0)
        lea     scr_llen+108(a0),a0
        subq.w  #1,d2
        bne.s   .c3
        bra.s   .noer
.c2:    movem.l d0-d1/d3/d5-d6/a1-a3/a5,-(a0)
        movem.l d0-d1/d3/d5-d6/a1-a3/a5,-(a0)
        lea     scr_llen+72(a0),a0
        subq.w  #1,d2
        bne.s   .c2
        bra.s   .noer
.c1:    movem.l d0-d1/d3/d5-d6/a1-a3/a5,-(a0)
        lea     scr_llen+36(a0),a0
        subq.w  #1,d2
        bne.s   .c1
.noer:

; ----- rotate: advance angles by the previous loop's beats (constant
; angular speed in TIME), look up sin/cos into trig(pc)
        lea     angles(pc),a0
        lea     sintab(pc),a1
        lea     trig(pc),a2
        move.w  headroom+16(pc),d2  ; beats of the previous loop (1|2)
        move.w  d2,d1
        muls.w  #da,d1              ; yaw step
        move.w  (a0),d0
        add.w   d1,d0               ; word wrap = mod 256 brads
        move.w  d0,(a0)
        lsr.w   #8,d0               ; integer brad
        add.w   d0,d0
        move.w  (a1,d0.w),d1
        move.w  d1,(a2)             ; sa
        lsr.w   #1,d0
        add.w   #64,d0              ; cos = sin(a+64)
        and.w   #255,d0
        add.w   d0,d0
        move.w  (a1,d0.w),d1
        move.w  d1,2(a2)            ; ca
        move.w  d2,d1
        muls.w  #db,d1              ; pitch step
        move.w  2(a0),d0
        add.w   d1,d0
        move.w  d0,2(a0)
        lsr.w   #8,d0
        add.w   d0,d0
        move.w  (a1,d0.w),d1
        move.w  d1,4(a2)            ; sb
        lsr.w   #1,d0
        add.w   #64,d0
        and.w   #255,d0
        add.w   d0,d0
        move.w  (a1,d0.w),d1
        move.w  d1,6(a2)            ; cb

; ----- transform + project the 8 vertices into vtx2d
        lea     verts(pc),a0
        lea     vtx2d(pc),a1
        moveq   #8-1,d6
.vtx:   move.w  (a0)+,d0            ; x
        move.w  (a0)+,d1            ; y
        move.w  (a0)+,d2            ; z
        move.w  d0,d3               ; yaw: x' = (x*ca + z*sa) >> 8
        muls.w  2(a2),d3
        move.w  d2,d4
        muls.w  (a2),d4
        add.l   d4,d3
        asr.l   #8,d3               ; d3 = x'
        muls.w  2(a2),d2            ; z' = (z*ca - x*sa) >> 8
        muls.w  (a2),d0
        sub.l   d0,d2
        asr.l   #8,d2               ; d2 = z'
        move.w  d1,d4               ; pitch: y' = (y*cb - z'*sb) >> 8
        muls.w  6(a2),d4
        move.w  d2,d5
        muls.w  4(a2),d5
        sub.l   d5,d4
        asr.l   #8,d4               ; d4 = y'
        muls.w  4(a2),d1            ; z'' = (y*sb + z'*cb) >> 8
        muls.w  6(a2),d2
        add.l   d2,d1
        asr.l   #8,d1               ; d1 = z''
        add.w   #zdist,d1           ; d1 = Z0 + z'' (always > 0)
        move.w  d3,d0               ; perspective x
        ext.l   d0
        asl.l   #8,d0               ; x' * xfocal (= 256)
        divs.w  d1,d0
        add.w   #ctr_x,d0
        move.w  d0,(a1)+            ; px
        muls.w  #yfocal,d4          ; perspective y
        divs.w  d1,d4
        add.w   #ctr_y,d4
        move.w  d4,(a1)+            ; py
        dbf     d6,.vtx

; ----- bounding box of the new projection (for this buffer's NEXT erase)
        lea     vtx2d(pc),a0
        move.w  (a0)+,d0            ; minx = maxx = x0
        move.w  d0,d1
        move.w  (a0)+,d2            ; miny = maxy = y0
        move.w  d2,d3
        moveq   #7-1,d6
.bb:    move.w  (a0)+,d4
        cmp.w   d4,d0
        ble.s   .b1
        move.w  d4,d0
.b1:    cmp.w   d4,d1
        bge.s   .b2
        move.w  d4,d1
.b2:    move.w  (a0)+,d4
        cmp.w   d4,d2
        ble.s   .b3
        move.w  d4,d2
.b3:    cmp.w   d4,d3
        bge.s   .b4
        move.w  d4,d3
.b4:    dbf     d6,.bb
        lea     bbox0(pc),a2
        move.w  d7,d4
        lsl.w   #3,d4
        adda.w  d4,a2
        move.w  d2,(a2)+            ; miny
        sub.w   d2,d3
        addq.w  #1,d3
        move.w  d3,(a2)+            ; nrows
        lsr.w   #5,d0               ; 32-px (8-byte) units
        lsr.w   #5,d1
        sub.w   d0,d1               ; units spanned - 1 (0..15)
        lsl.w   #3,d0               ; start byte offset
        moveq   #0,d4               ; chunks needed for (units+1)*8
        add.w   #36,d0              ; bytes: end offset grows a chunk
        cmp.w   #3,d1               ; at a time. <= 32 bytes: 1 chunk
        ble.s   .cok
        addq.w  #1,d4
        add.w   #36,d0
        cmp.w   #8,d1               ; <= 72 bytes: 2
        ble.s   .cok
        addq.w  #1,d4
        add.w   #36,d0
        cmp.w   #12,d1              ; <= 104 bytes: 3
        ble.s   .cok
        addq.w  #1,d4
        add.w   #36,d0              ; 4 chunks = 144, covers max 128
.cok:   move.w  d0,(a2)+            ; end-of-span offset
        move.w  d4,(a2)             ; chunk count - 1

; ----- backface culling: build the face-visibility mask in d5.
; Screen coords have y growing DOWN, and the face tables are wound so a
; front-facing face projects with cross > 0:
;   cross = (bx-ax)*(cy-ay) - (by-ay)*(cx-ax)   (long: terms reach ~40000)
; The faces table is ordered F5 first so the dbf counter is the bit no.
        lea     faces(pc),a0
        lea     vtx2d(pc),a3        ; a3 stays vtx2d through the draws
        moveq   #0,d5
        moveq   #6-1,d6
.face:  moveq   #0,d0
        move.b  (a0)+,d0            ; vertex a (offsets pre-multiplied)
        moveq   #0,d1
        move.b  (a0)+,d1            ; vertex b
        moveq   #0,d2
        move.b  (a0)+,d2            ; vertex c
        move.w  (a3,d1.w),d3        ; bx - ax
        sub.w   (a3,d0.w),d3
        move.w  2(a3,d2.w),d4       ; cy - ay
        sub.w   2(a3,d0.w),d4
        muls.w  d4,d3
        move.w  2(a3,d1.w),d4       ; by - ay
        sub.w   2(a3,d0.w),d4
        move.w  (a3,d2.w),d1        ; cx - ax
        sub.w   (a3,d0.w),d1
        muls.w  d1,d4
        sub.l   d4,d3               ; cross
        ble.s   .hid                ; <= 0: backface (or edge-on)
        bset    d6,d5
.hid:   dbf     d6,.face
        move.w  d5,a5               ; park the mask across the draws

; ----- draw the edges whose faces are not all hidden
        lea     edges(pc),a2
        moveq   #12-1,d6
.edge:  move.w  a5,d0
        and.b   2(a2),d0            ; edge's two-face mask vs visibility
        beq.s   .skip
        moveq   #0,d2
        move.b  (a2),d0             ; vertex offsets (pre-multiplied)
        move.b  1(a2),d2
        and.w   #$ff,d0
        move.w  2(a3,d0.w),d1       ; y1
        move.w  (a3,d0.w),d0        ; x1
        move.w  2(a3,d2.w),d3       ; y2
        move.w  (a3,d2.w),d2        ; x2
        bsr     draw_line_w
.skip:  addq.l  #3,a2
        dbf     d6,.edge

; ----- headroom bar + meters, then VBL sync + flip. A pending frame
; bit at end-of-work means the work crossed a VBL: this loop takes two
; beats (25 Hz). Consume it, then wait for the next real edge so flips
; stay VBL-aligned however long drawing took. The live bar shows this
; loop's idle spins; the meters average 64 loops (see draw_meters).
        bsr     draw_hbar
        bsr     draw_meters
        moveq   #0,d1               ; d1 = 1 if this was a 2-beat loop
        btst    #pc__frame,pc_intr
        beq.s   .onb
        moveq   #1,d1
        move.b  #1<<pc__frame,pc_intr   ; consume the mid-work edge
.onb:   moveq   #0,d0
.wait:  addq.l  #1,d0               ; count idle spins = headroom
        btst    #pc__frame,pc_intr
        beq.s   .wait
        move.b  #1<<pc__frame,pc_intr   ; consume the terminal edge, so
                                    ; next loop's pending-test is honest
        lea     headroom(pc),a2
        move.l  d0,(a2)
        add.l   d0,4(a2)            ; window accumulators: spins,
        add.w   d1,8(a2)            ; 2-beat loops,
        addq.w  #1,d1
        move.w  d1,16(a2)           ; beats for the rotation step
        subq.w  #1,10(a2)           ; loops left in the window
        bne.s   .flip
        move.w  #64,10(a2)
        move.l  4(a2),d0            ; latch: avg spins/loop,
        lsr.l   #6,d0
        move.w  d0,12(a2)
        move.w  8(a2),14(a2)        ; 2-beat count of the 64
        clr.l   4(a2)
        clr.w   8(a2)
.flip:

        move.w  d7,d0               ; flip: display the buffer just drawn
        ror.b   #1,d0               ; 0 -> $00, 1 -> $80
        move.b  d0,mc_stat
        eori.w  #1,d7               ; other buffer becomes the back one
        bra     frame_loop

; ------------------------------------------------------------------- meters
; Two 16-bit binary readouts (the lines/ instrument: MSB left, 8-px
; cell per bit, dashed ruler under each), averaged over 64 loops so
; they hold steady -- the live bar is honest but teleports near the
; 20 ms boundary, where one VBL more or less flips the beat count:
;   rows 240-242: average idle spins per loop (1 spin ~ 20 us)
;   rows 245-247: 2-beat loops out of 64 (0 = pure 50 Hz, 64 = 25 Hz)
draw_meters:
        lea     headroom+12(pc),a1
        move.w  (a1)+,d0
        lea     240*scr_llen+48(a4),a0
        bsr.s   draw_ro
        move.w  (a1),d0
        lea     245*scr_llen+48(a4),a0
draw_ro:                            ; (fallthrough: 2nd readout's rts
        moveq   #16-1,d2            ;  returns to draw_meters' caller)
.cell:  moveq   #0,d1
        add.w   d0,d0               ; MSB out into carry
        bcc.s   .un
        move.b  #$fc,d1             ; lit: 6 px block + 2 px gap
.un:    move.b  d1,(a0)             ; green byte, 2 value rows
        move.b  d1,scr_llen(a0)
        move.b  #$fc,2*scr_llen(a0) ; ruler row
        addq.l  #2,a0
        dbf     d2,.cell
        rts

; -------------------------------------------------------------- headroom bar
; game8's gauge in mode 4: 64 groups of 8 px, lit = green byte $ff.
; The unlit remainder is written black, so the bar self-erases.
draw_hbar:
        lea     headroom(pc),a1
        move.l  (a1),d0
        lsr.l   #hb_shift,d0
        cmp.w   #64,d0
        bls.s   .clip
        moveq   #64,d0
.clip:  lea     hb_y*scr_llen(a4),a0
        moveq   #2-1,d3
.row:   move.w  d0,d1               ; lit groups
        moveq   #64,d2
        sub.w   d0,d2               ; dark groups
        tst.w   d1
        beq.s   .dark
        subq.w  #1,d1
.lit:   move.b  #$ff,(a0)+          ; green byte
        clr.b   (a0)+               ; red byte
        dbf     d1,.lit
.dark:  tst.w   d2
        beq.s   .next
        subq.w  #1,d2
.drk:   clr.b   (a0)+
        clr.b   (a0)+
        dbf     d2,.drk
.next:  dbf     d3,.row             ; 128 bytes written = next line
        rts

; ---------------------------------------------------------------------- data
        even
angles: dc.w    0,0                 ; yaw, pitch (brads 0..255)
trig:   dc.w    0,0,0,0             ; sa, ca, sb, cb (8.8, set per frame)
headroom:
        dc.l    0                   ; idle spins in last loop's VBL wait
        dc.l    0                   ; +4  window: spins accumulator
        dc.w    0                   ; +8  window: 2-beat loop count
        dc.w    64                  ; +10 loops left in the window
        dc.w    0                   ; +12 latched avg spins (meter A)
        dc.w    0                   ; +14 latched 2-beat count (meter B)
        dc.w    1                   ; +16 beats of the last loop (1|2)

; per-buffer erase boxes: miny, nrows, byte offset, long-pair count-1
bbox0:  dc.w    0,0,0,0             ; nrows = 0: nothing to erase yet
bbox1:  dc.w    0,0,0,0

verts:                              ; the 8 corners, x,y,z words
        dc.w    -csize,-csize,-csize
        dc.w     csize,-csize,-csize
        dc.w     csize, csize,-csize
        dc.w    -csize, csize,-csize
        dc.w    -csize,-csize, csize
        dc.w     csize,-csize, csize
        dc.w     csize, csize, csize
        dc.w    -csize, csize, csize

; faces: 3 test vertices each (offsets = index*4), wound so that viewed
; from OUTSIDE the winding is consistent -- shared edges traversed in
; opposite directions. Ordered F5-first: the cull loop's dbf counter is
; the face's bit number.
faces:
        dc.b    5*4,4*4,7*4         ; F5 far (z=+s)      -> bit 5
        dc.b    0*4,3*4,7*4         ; F4 left (x=-s)     -> bit 4
        dc.b    3*4,2*4,6*4         ; F3 bottom (y=+s)   -> bit 3
        dc.b    2*4,1*4,5*4         ; F2 right (x=+s)    -> bit 2
        dc.b    1*4,0*4,4*4         ; F1 top (y=-s)      -> bit 1
        dc.b    0*4,1*4,2*4         ; F0 near (z=-s)     -> bit 0

; edges: two vertex offsets + the mask of the two faces meeting there
edges:
        dc.b    0*4,1*4,%00000011   ; F0+F1
        dc.b    1*4,2*4,%00000101   ; F0+F2
        dc.b    2*4,3*4,%00001001   ; F0+F3
        dc.b    3*4,0*4,%00010001   ; F0+F4
        dc.b    4*4,5*4,%00100010   ; F5+F1
        dc.b    5*4,6*4,%00100100   ; F5+F2
        dc.b    6*4,7*4,%00101000   ; F5+F3
        dc.b    7*4,4*4,%00110000   ; F5+F4
        dc.b    0*4,4*4,%00010010   ; F1+F4
        dc.b    1*4,5*4,%00000110   ; F1+F2
        dc.b    2*4,6*4,%00001100   ; F2+F3
        dc.b    3*4,7*4,%00011000   ; F3+F4
        even

vtx2d:  ds.w    16                  ; projected x,y per vertex

        include "sin.inc"

        even
sv_stack:
        ds.b    64                  ; private supervisor stack
sv_stack_top:

        include "../lib/draw_line_w.asm"
