; cube.asm -- rotating wireframe cube: the first 3D milestone
;
; MODE 4, full takeover, double buffering on the two hardware screens
; (docs/takeover.md), built on the measured line budget in
; docs/vector-perf.md: at ~90 px edges the cube costs ~1.8 frames to
; erase + transform + draw, so it runs at a steady 25 Hz -- only
; complete frames are ever shown. Getting it to 50 Hz is future work.
;
; Per frame, into the back buffer:
;   1. erase: long-word clear of the bounding box the cube had in THIS
;      buffer two frames ago (32-px-aligned spans; far cheaper than
;      redrawing the old edges in black -- and the reason the cube is
;      WHITE: both planes clear together)
;   2. rotate: yaw then pitch, 8.8 fixed-point sin/cos from sintab
;      (sin.inc, generated by tools/gensin.py)
;   3. project: perspective, px = 256 + x'*256/(Z0+z), and the y focal
;      length scaled to 170 (~2/3) because mode 4 pixels are ~2/3 as
;      wide as tall on a 4:3 screen -- the cube LOOKS cubic
;   4. draw the 12 edges with lib/draw_line_w.asm (white, shallow lines
;      through the byte-granular fast path)
;   5. headroom bar (game8's honest gauge): green bar at the bottom =
;      idle spins in the VBL wait; toward zero = over budget. At 25 Hz
;      the bar shows the slack of the second frame.
;
; No clipping: S/Z0/focal are chosen so the projection stays on screen
; (max extent x 256+-98, y 120+-66) clear of the bar rows.
;
; Assemble: vasmm68k_mot -m68008 -Fbin -o cube_bin cube.asm

; hardware
mc_stat     equ     $18063          ; ZX8301 display control (write-only)
pc_intr     equ     $18021          ; ZX8302 interrupt register
pc__frame   equ     3               ; bit 3 = 50/60 Hz frame interrupt

scr0        equ     $20000          ; screen 0 (displayed at boot)
scr1        equ     $28000          ; screen 1 (ex-QDOS sysvars, now ours)
scr_llen    equ     128             ; bytes per scan line

; cube geometry / projection (see the no-clipping note above)
csize       equ     48              ; half edge: vertices at (+-48)^3
zdist       equ     300             ; Z0: eye distance to cube centre
xfocal      equ     256             ; px = 256 + x'*xfocal/(Z0+z)
yfocal      equ     170             ; py = 120 + y'*yfocal/(Z0+z)
ctr_x       equ     256
ctr_y       equ     120

da          equ     2               ; yaw brads/frame   (256 = full turn)
db          equ     3               ; pitch brads/frame

; headroom bar (game8 calibration: ~1000 idle spins = a whole free frame)
hb_y        equ     252             ; bar top line (2 rows tall)
hb_shift    equ     4

; ---------------------------------------------------------------- job header
start:
        bra.s   main
        dc.l    0
        dc.w    $4afb               ; "job name follows" flag
        dc.w    jobname_e-jobname
jobname:
        dc.b    'Cube'
jobname_e:
        even

; ----------------------------------------------------------------- take over
main:
        trap    #0                  ; QDOS: enter supervisor mode
        move.w  #$2700,sr           ; mask all interrupts -- QDOS is gone
        lea     sv_stack_top(pc),sp ; run on our own supervisor stack

        move.b  #0,mc_stat          ; mode 4, screen 0 displayed

        lea     scr0,a0             ; clear BOTH screens ($20000-$2FFFF)
        move.w  #$10000/4-1,d0
        moveq   #0,d1
.clr:   move.l  d1,(a0)+
        dbf     d0,.clr

        move.b  #1<<pc__frame,pc_intr   ; discard any pending frame bit
        moveq   #1,d7               ; back buffer index: screen 1

; ---------------------------------------------------------------- frame loop
frame_loop:
        lea     scr0,a4             ; a4 = back buffer base
        tst.w   d7
        beq.s   .bb0
        lea     scr1,a4
.bb0:
; ----- erase the cube this buffer held two frames ago: clear its
; bounding box rows in 32-px-aligned long pairs (bbox: miny, nrows,
; byte offset, long-pair count-1; nrows = 0 -> nothing yet)
        lea     bbox0(pc),a2
        move.w  d7,d0
        lsl.w   #3,d0
        adda.w  d0,a2               ; a2 = bbox[d7]
        move.w  (a2)+,d1            ; miny
        move.w  (a2)+,d2            ; nrows
        beq.s   .noer
        move.w  (a2)+,d3            ; byte offset in the row
        move.w  (a2)+,d4            ; long pairs - 1
        lsl.w   #7,d1
        add.w   d3,d1
        lea     (a4,d1.w),a0
        moveq   #0,d0
.erow:  move.l  a0,a1
        move.w  d4,d5
.epl:   move.l  d0,(a1)+            ; 16 px, both planes
        move.l  d0,(a1)+
        dbf     d5,.epl
        lea     scr_llen(a0),a0
        subq.w  #1,d2
        bne.s   .erow
.noer:

; ----- rotate: advance angles, look up sin/cos into trig(pc)
        lea     angles(pc),a0
        lea     sintab(pc),a1
        lea     trig(pc),a2
        move.w  (a0),d0             ; yaw
        addq.w  #da,d0
        and.w   #255,d0
        move.w  d0,(a0)
        add.w   d0,d0
        move.w  (a1,d0.w),d1
        move.w  d1,(a2)             ; sa
        lsr.w   #1,d0
        add.w   #64,d0              ; cos = sin(a+64)
        and.w   #255,d0
        add.w   d0,d0
        move.w  (a1,d0.w),d1
        move.w  d1,2(a2)            ; ca
        move.w  2(a0),d0            ; pitch
        addq.w  #db,d0
        and.w   #255,d0
        move.w  d0,2(a0)
        add.w   d0,d0
        move.w  (a1,d0.w),d1
        move.w  d1,4(a2)            ; sb
        lsr.w   #1,d0
        add.w   #64,d0
        and.w   #255,d0
        add.w   d0,d0
        move.w  (a1,d0.w),d1
        move.w  d1,6(a2)            ; cb

; ----- transform + project the 8 vertices into vtx2d
        lea     verts(pc),a0
        lea     vtx2d(pc),a1
        moveq   #8-1,d6
.vtx:   move.w  (a0)+,d0            ; x
        move.w  (a0)+,d1            ; y
        move.w  (a0)+,d2            ; z
        move.w  d0,d3               ; yaw: x' = (x*ca + z*sa) >> 8
        muls.w  2(a2),d3
        move.w  d2,d4
        muls.w  (a2),d4
        add.l   d4,d3
        asr.l   #8,d3               ; d3 = x'
        muls.w  2(a2),d2            ; z' = (z*ca - x*sa) >> 8
        muls.w  (a2),d0
        sub.l   d0,d2
        asr.l   #8,d2               ; d2 = z'
        move.w  d1,d4               ; pitch: y' = (y*cb - z'*sb) >> 8
        muls.w  6(a2),d4
        move.w  d2,d5
        muls.w  4(a2),d5
        sub.l   d5,d4
        asr.l   #8,d4               ; d4 = y'
        muls.w  4(a2),d1            ; z'' = (y*sb + z'*cb) >> 8
        muls.w  6(a2),d2
        add.l   d2,d1
        asr.l   #8,d1               ; d1 = z''
        add.w   #zdist,d1           ; d1 = Z0 + z'' (always > 0)
        move.w  d3,d0               ; perspective x
        ext.l   d0
        asl.l   #8,d0               ; x' * xfocal (= 256)
        divs.w  d1,d0
        add.w   #ctr_x,d0
        move.w  d0,(a1)+            ; px
        muls.w  #yfocal,d4          ; perspective y
        divs.w  d1,d4
        add.w   #ctr_y,d4
        move.w  d4,(a1)+            ; py
        dbf     d6,.vtx

; ----- bounding box of the new projection (for this buffer's NEXT erase)
        lea     vtx2d(pc),a0
        move.w  (a0)+,d0            ; minx = maxx = x0
        move.w  d0,d1
        move.w  (a0)+,d2            ; miny = maxy = y0
        move.w  d2,d3
        moveq   #7-1,d6
.bb:    move.w  (a0)+,d4
        cmp.w   d4,d0
        ble.s   .b1
        move.w  d4,d0
.b1:    cmp.w   d4,d1
        bge.s   .b2
        move.w  d4,d1
.b2:    move.w  (a0)+,d4
        cmp.w   d4,d2
        ble.s   .b3
        move.w  d4,d2
.b3:    cmp.w   d4,d3
        bge.s   .b4
        move.w  d4,d3
.b4:    dbf     d6,.bb
        lea     bbox0(pc),a2
        move.w  d7,d4
        lsl.w   #3,d4
        adda.w  d4,a2
        move.w  d2,(a2)+            ; miny
        sub.w   d2,d3
        addq.w  #1,d3
        move.w  d3,(a2)+            ; nrows
        lsr.w   #5,d0               ; 32-px units
        lsr.w   #5,d1
        sub.w   d0,d1               ; long pairs - 1
        lsl.w   #3,d0               ; byte offset = unit * 8
        move.w  d0,(a2)+
        move.w  d1,(a2)

; ----- draw the 12 edges
        lea     edges(pc),a2
        moveq   #12-1,d6
.edge:  moveq   #0,d2
        move.b  (a2)+,d0            ; vertex offsets (pre-multiplied by 4)
        move.b  (a2)+,d2
        and.w   #$ff,d0
        lea     vtx2d(pc),a1
        move.w  2(a1,d0.w),d1       ; y1
        move.w  (a1,d0.w),d0        ; x1
        move.w  2(a1,d2.w),d3       ; y2
        move.w  (a1,d2.w),d2        ; x2
        bsr     draw_line_w
        dbf     d6,.edge

; ----- headroom bar, then VBL sync + flip. Ack FIRST: at 25 Hz that
; consumes the VBL that fired mid-drawing, and the wait locks the flip
; to the next real edge -- flips stay VBL-aligned however long drawing
; took. The bar therefore measures the slack of the frame pair.
        bsr     draw_hbar
        move.b  #1<<pc__frame,pc_intr   ; consume any pending edge
        moveq   #0,d0
.wait:  addq.l  #1,d0               ; count idle spins = headroom
        btst    #pc__frame,pc_intr
        beq.s   .wait
        lea     headroom(pc),a2
        move.l  d0,(a2)

        move.w  d7,d0               ; flip: display the buffer just drawn
        ror.b   #1,d0               ; 0 -> $00, 1 -> $80
        move.b  d0,mc_stat
        eori.w  #1,d7               ; other buffer becomes the back one
        bra     frame_loop

; -------------------------------------------------------------- headroom bar
; game8's gauge in mode 4: 64 groups of 8 px, lit = green byte $ff.
; The unlit remainder is written black, so the bar self-erases.
draw_hbar:
        lea     headroom(pc),a1
        move.l  (a1),d0
        lsr.l   #hb_shift,d0
        cmp.w   #64,d0
        bls.s   .clip
        moveq   #64,d0
.clip:  lea     hb_y*scr_llen(a4),a0
        moveq   #2-1,d3
.row:   move.w  d0,d1               ; lit groups
        moveq   #64,d2
        sub.w   d0,d2               ; dark groups
        tst.w   d1
        beq.s   .dark
        subq.w  #1,d1
.lit:   move.b  #$ff,(a0)+          ; green byte
        clr.b   (a0)+               ; red byte
        dbf     d1,.lit
.dark:  tst.w   d2
        beq.s   .next
        subq.w  #1,d2
.drk:   clr.b   (a0)+
        clr.b   (a0)+
        dbf     d2,.drk
.next:  dbf     d3,.row             ; 128 bytes written = next line
        rts

; ---------------------------------------------------------------------- data
        even
angles: dc.w    0,0                 ; yaw, pitch (brads 0..255)
trig:   dc.w    0,0,0,0             ; sa, ca, sb, cb (8.8, set per frame)
headroom:
        dc.l    0                   ; idle spins in last frame's VBL wait

; per-buffer erase boxes: miny, nrows, byte offset, long-pair count-1
bbox0:  dc.w    0,0,0,0             ; nrows = 0: nothing to erase yet
bbox1:  dc.w    0,0,0,0

verts:                              ; the 8 corners, x,y,z words
        dc.w    -csize,-csize,-csize
        dc.w     csize,-csize,-csize
        dc.w     csize, csize,-csize
        dc.w    -csize, csize,-csize
        dc.w    -csize,-csize, csize
        dc.w     csize,-csize, csize
        dc.w     csize, csize, csize
        dc.w    -csize, csize, csize

edges:                              ; 12 edges, vertex offsets (index*4)
        dc.b    0*4,1*4, 1*4,2*4, 2*4,3*4, 3*4,0*4    ; back face
        dc.b    4*4,5*4, 5*4,6*4, 6*4,7*4, 7*4,4*4    ; front face
        dc.b    0*4,4*4, 1*4,5*4, 2*4,6*4, 3*4,7*4    ; connecting
        even

vtx2d:  ds.w    16                  ; projected x,y per vertex

        include "sin.inc"

        even
sv_stack:
        ds.b    64                  ; private supervisor stack
sv_stack_top:

        include "../lib/draw_line_w.asm"
