#!/usr/bin/env python3
"""Emit a 256-step sine table (8.8 fixed point, 256 = 1.0) as vasm dc.w
lines on stdout. Cosine is read from the same table at index (a+64)&255.
Used by cube/Makefile to generate sin.inc."""
import math

print("; generated by tools/gensin.py -- do not edit")
print("; sin(i * 2*pi/256) * 256, 256 entries")
print("sintab:")
for base in range(0, 256, 8):
    row = ",".join(str(round(math.sin(i * 2 * math.pi / 256) * 256))
                   for i in range(base, base + 8))
    print(f"        dc.w    {row}")
