#!/usr/bin/env python3
"""gensparks -- explosion spark patterns for glider (spec 5.6).

Usage, from glider/:  python ../tools/gensparks.py > sparks.inc

A burst is precomputed here, one step per beat, so the game does no
spark physics: each spark flies out from the victim's centre with a
random speed and an upward bias, falls under gravity, bounces on the
ground at a third of its speed and dies after 12..20 beats. The game
projects the offsets with the victim's depth (spec 5.6: camera-aligned
axes, no rotation -- a burst is isotropic), so only the across (x) and
down (y) components are stored, in units of SCALE world units, y down.
A pattern is three words of extent (below), then LIFE word offsets
(one per age, from the pattern's label) to its rows; a row is the
count of live sparks (a byte), then that many (x, y) pairs of signed
bytes -- the dead ones are left out, so the game's loop never meets
one. With it, the extent
of the whole burst (largest |x|, smallest and largest y) lets the game
skip the per-spark screen bounds when the burst is wholly on screen.
Stdlib only, seeded: the output is the same every run.
"""

import math
import random
import sys

NSPARK = 16             # sparks per burst
LIFE = 20               # table length in beats (the longest life)
LIFE_MIN = 12
SCALE = 2               # world units per stored unit (bytes reach +-254)
GRAVITY = 1.8           # units per beat per beat, y down (arcade:
                        # about half the sparks reach the ground)
SPEED = (6.0, 13.0)     # launch speed range, units per beat
UPBIAS = 7.0            # added upward speed, units per beat
BOUNCE = 1.0 / 3.0      # speed kept by a bounce

# One pattern per ground distance below the victim's centre (y down):
# the mine floats with its centre at cam_h (128).
PATTERNS = [("mine", 128, 272)] # name, ground below the centre, seed
                                # (272: a balanced burst, mean x ~0)
DEAD = -128


def burst(ground, seed):
    rnd = random.Random(seed)
    rows = [[] for _ in range(LIFE)]
    for k in range(NSPARK):
        # a direction uniform on the sphere, then an upward push
        z = rnd.uniform(-1.0, 1.0)
        a = rnd.uniform(0.0, 2.0 * math.pi)
        r = math.sqrt(1.0 - z * z)
        sp = rnd.uniform(*SPEED)
        vx = r * math.cos(a) * sp           # across the screen
        vy = z * sp - UPBIAS                # down; negative = up
        life = rnd.randint(LIFE_MIN, LIFE)
        x = y = 0.0
        for age in range(LIFE):
            if age >= life:
                rows[age].append((DEAD, DEAD))
                continue
            bx = max(-127, min(127, round(x / SCALE)))
            by = max(-127, min(127, round(y / SCALE)))
            rows[age].append((bx, by))
            x += vx                         # one beat
            vy += GRAVITY
            y += vy
            if y > ground:                  # through the ground: bounce
                y = ground - (y - ground) * BOUNCE
                vy = -vy * BOUNCE
                vx *= BOUNCE
    return rows


def main():
    print("; generated by tools/gensparks.py -- do not edit")
    print(f"spk_n       equ     {NSPARK}           ; sparks per burst")
    print(f"spk_life    equ     {LIFE}           ; beats a burst lasts")
    print(f"spk_scale   equ     {SCALE}            ; world units per stored unit")
    for name, ground, seed in PATTERNS:
        rows = burst(ground, seed)
        live = [[xy for xy in row if xy[0] != DEAD] for row in rows]
        xs = [x for row in live for x, y in row]
        ys = [y for row in live for x, y in row]
        print(f"; ----- {name}: ground {ground} below the centre, seed {seed}")
        print(f"spk_{name}:")
        print(f"        dc.w    {max(abs(x) for x in xs)},{min(ys)},{max(ys)}"
              "   ; extent: largest |x|, smallest y, largest y")
        for age in range(LIFE):                 # per age, the row's offset
            print(f"        dc.w    spk_{name}_{age}-spk_{name}")
        for age, row in enumerate(live):
            vals = ",".join(str(v & 0xFF) for xy in row for v in xy)
            print(f"spk_{name}_{age}:")
            print(f"        dc.b    {len(row)}" + (f",{vals}" if vals else ""))
        print(f"; {name}: live sparks per age {[len(r) for r in live]}", file=sys.stderr)
    print("        even")


if __name__ == "__main__":
    main()
